<a href="https://colab.research.google.com/github/bmarcarrera/Mundial_Futbol/blob/main/Ganadores_de_mundiales_y_caracter%C3%ADsticas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <u>Estadísticas generales ganadores de los mundiales de fútbol</u>

A continuación, se presentan los datos más relevantes de todos los mundiales de fútbol celebrados, ordenados en función de la selección ganadora en cada evento, a partir de un *archivo.csv* que contiene la información más relevante de cada Mundial celebrado desde 1930 hasta 2022.

Se ha generado un DataFrame limpio utilizando la librería Pandas de Python utilizando los siguientes parámetros:

    - Campeón
    - Copas ganadas
    - Años ganados
    - Subcampeones
    - Máximo goleador del campeonato
    - País anfitrión

## Importar Pandas

In [242]:
import pandas as pd

## Importar archivo *.csv*

In [243]:
mundiales_csv = "https://github.com/bmarcarrera/Mundial_Futbol/blob/main/world_cup.csv"

## Crear *DataFrame* con *Pandas*

Se genera un *DataFrame* a partir del archivo importado y poder manipular los datos de forma más visual y sencilla.

In [244]:
df_mundiales = pd.read_csv(mundiales_csv)
df_mundiales

## Cambiar el nombre de determinados valores

Se cambia al idioma español los nombres de los países de forma manual.

In [246]:
paises = {
    "France": "Francia",
    "Croatia": "Croacia",
    "Netherlands":  "Holanda",
    "Germany": "Alemania",
    "West Germany": "Alemania",
    "Brazil": "Brasil",
    "Italy": "Italia",
    "Czechoslovakia": "Checoslovaquia",
    "Sweden": "Suecia",
    "Hungary": "Hungría",
    "Switzerland": "Suiza",
    "England": "Inglaterra",
    "Spain": "España",
    "United States": "USA",
    "Korea Republic, Japan": "Corea del Sur, Japón",
    "South Africa": "Sudáfrica",
    "Russia": "Rusia",
    "Qatar": "Catar"
}

In [247]:
df_mundiales[["Champion", "Runner-Up", "Host"]] = df_mundiales[["Champion", "Runner-Up", "Host"]].replace(paises)
df_mundiales

,Year,Host,Teams,Champion,Runner-Up,TopScorrer,Attendance,AttendanceAvg,Matches
0,2022,Catar,32,Argentina,Francia,Kylian Mbappé - 8,3404252,53191,64
1,2018,Rusia,32,Francia,Croacia,Harry Kane - 6,3031768,47371,64
2,2014,Brasil,32,Alemania,Argentina,James Rodríguez - 6,3429873,53592,64
3,2010,Sudáfrica,32,España,Holanda,"Wesley Sneijder, Thomas Müller... - 5",3178856,49670,64
4,2006,Alemania,32,Italia,Francia,Miroslav Klose - 5,3352605,52384,64
5,2002,"Corea del Sur, Japón",32,Brasil,Alemania,Ronaldo - 8,2705337,42271,64
6,1998,Francia,32,Francia,Brasil,Davor Šuker - 6,2903477,45367,64
7,1994,USA,24,Brasil,Italia,"Hristo Stoichkov, Oleg Salenko - 6",3587538,68991,52
8,1990,Italia,24,Alemania,Argentina,Salvatore Schillaci - 6,2516215,48389,52
9,1986,Mexico,24,Argentina,Alemania,Gary Lineker - 6,2394031,46039,52
10,1982,España,24,Italia,Alemania,Paolo Rossi - 6,2109723,40572,52
11,1978,Argentina,16,Argentina,Holanda,Mario Kempes - 6,1545791,40679,38
12,1974,Alemania,16,Alemania,Holanda,Grzegorz Lato - 7,1865753,49099,38
13,1970,Mexico,16,Brasil,Italia,Gerd Müller - 10,1603975,50124,32
14,1966,Inglaterra,16,Inglaterra,Alemania,Eusébio - 9,1563135,48848,32
15,1962,Chile,16,Brasil,Checoslovaquia,"Leonel Sánchez, Flórián Albert... - 4",893172,27912,32
16,1958,Suecia,16,Brasil,Suecia,Just Fontaine - 13,819810,23423,35
17,1954,Suiza,16,Alemania,Hungría,Sándor Kocsis - 11,768607,29562,26
18,1950,Brasil,15,Uruguay,Brasil,Ademir - 8,1045246,47511,22
19,1938,Francia,16,Italia,Hungría,Leônidas - 7,375700,20872,18
20,1934,Italia,16,Italia,Checoslovaquia,Oldřich Nejedlý - 5,363000,21353,17
21,1930,Uruguay,13,Uruguay,Argentina,Guillermo Stábile - 8,590549,32808,18

## Selección de las columnas para nuestro nuevo *Dataframe*

Para ello, también usaremos la función *.copy()* para crear uno independiente del original.

In [248]:
columnas_original_permanecen = ["Year", "Host", "Champion", "Runner-Up", "TopScorrer"]
df_nuevo = df_mundiales[columnas_original_permanecen].copy()

## Agrupación de valores en función de una columna

Se agrupan los valores en cada columna en función del campeón para poder establecer el récord de cada selección campeona, los años que ganó, el subcampeón, el máximo goleador de la edición y el anfitrión donde se proclamó campeona dicha selección.

In [249]:
df_nuevo = df_nuevo.groupby("Champion", as_index= False).agg(
    winner = ("Champion", "count"),
    year = ("Year", lambda year: ", ".join(year.astype(str))),
    runner_up = ("Runner-Up", ", ".join),
    top_scorer = ("TopScorrer", ", ".join),
    host = ("Host", ", ".join)
)


df_nuevo

,Champion,winner,year,runner_up,top_scorer,host
0,Alemania,4,"2014, 1990, 1974, 1954","Argentina, Argentina, Holanda, Hungría","James Rodríguez - 6, Salvatore Schillaci - 6, ...","Brasil, Italia, Alemania, Suiza"
1,Argentina,3,"2022, 1986, 1978","Francia, Alemania, Holanda","Kylian Mbappé - 8, Gary Lineker - 6, Mario Kem...","Catar, Mexico, Argentina"
2,Brasil,5,"2002, 1994, 1970, 1962, 1958","Alemania, Italia, Italia, Checoslovaquia, Suecia","Ronaldo - 8, Hristo Stoichkov, Oleg Salenko - ...","Corea del Sur, Japón, USA, Mexico, Chile, Suecia"
3,España,1,2010,Holanda,"Wesley Sneijder, Thomas Müller... - 5",Sudáfrica
4,Francia,2,"2018, 1998","Croacia, Brasil","Harry Kane - 6, Davor Šuker - 6","Rusia, Francia"
5,Inglaterra,1,1966,Alemania,Eusébio - 9,Inglaterra
6,Italia,4,"2006, 1982, 1938, 1934","Francia, Alemania, Hungría, Checoslovaquia","Miroslav Klose - 5, Paolo Rossi - 6, Leônidas ...","Alemania, España, Francia, Italia"
7,Uruguay,2,"1950, 1930","Brasil, Argentina","Ademir - 8, Guillermo Stábile - 8","Brasil, Uruguay"

## Renombrar columnas a español

In [250]:
columnas_nuevas = {
    "Champion": "Campeón",
    "year": "Años",
    "host": "Anfitriones",
    "runner_up": "Subcampeones",
    "top_scorer": "Máximo goleador",
    "winner": "Copas"
}

df_nuevo = df_nuevo.rename(columns=columnas_nuevas)
df_nuevo

,Campeón,Copas,Años,Subcampeones,Máximo goleador,Anfitriones
0,Alemania,4,"2014, 1990, 1974, 1954","Argentina, Argentina, Holanda, Hungría","James Rodríguez - 6, Salvatore Schillaci - 6, ...","Brasil, Italia, Alemania, Suiza"
1,Argentina,3,"2022, 1986, 1978","Francia, Alemania, Holanda","Kylian Mbappé - 8, Gary Lineker - 6, Mario Kem...","Catar, Mexico, Argentina"
2,Brasil,5,"2002, 1994, 1970, 1962, 1958","Alemania, Italia, Italia, Checoslovaquia, Suecia","Ronaldo - 8, Hristo Stoichkov, Oleg Salenko - ...","Corea del Sur, Japón, USA, Mexico, Chile, Suecia"
3,España,1,2010,Holanda,"Wesley Sneijder, Thomas Müller... - 5",Sudáfrica
4,Francia,2,"2018, 1998","Croacia, Brasil","Harry Kane - 6, Davor Šuker - 6","Rusia, Francia"
5,Inglaterra,1,1966,Alemania,Eusébio - 9,Inglaterra
6,Italia,4,"2006, 1982, 1938, 1934","Francia, Alemania, Hungría, Checoslovaquia","Miroslav Klose - 5, Paolo Rossi - 6, Leônidas ...","Alemania, España, Francia, Italia"
7,Uruguay,2,"1950, 1930","Brasil, Argentina","Ademir - 8, Guillermo Stábile - 8","Brasil, Uruguay"

## Exportar el *DataFrame* generado como un *archivo.csv*

In [251]:
df_nuevo.to_csv("Estadísticas_mundiales.csv", index=False, encoding="utf-8-sig")